name: Build OnePlus-Sm8150-KSU-Kernel-DerpFest
on:
  workflow_dispatch:
  schedule:
      # Run once a week on Sunday at midnight. See http://crontab.guru
      - cron: '0 21 * * *'
  push:
    branches:
      - 14
  pull_request:
      branches:
      - 14

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_MAXSIZE: "2G"
      CCACHE_HARDLINK: "true"
      KERNEL_DEFCONFIG: "vendor/derp_defconfig"
      KERNEL_CMDLINE: "ARCH=arm64 CLANG_TRIPLE=aarch64-linux-gnu- CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- O=out"
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: 'true'
        fetch-depth: 1
    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Remove unnecessary files
      run: |
        sudo rm -rf /opt/ghc
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
    - name: Install dependencies
      run: |
        sudo apt-get update -y 
        sudo apt install gcc-aarch64-linux-gnu -y
        sudo apt install gcc-arm-linux-gnueabi -y
        sudo apt install clang llvm lld ccache curl binutils make python3 libssl-dev build-essential bc bison flex unzip libssl-dev ca-certificates xz-utils mkbootimg cpio device-tree-compiler git git-lfs -y
        #git clone https://gitlab.com/LeCmnGend/proton-clang -b clang-14 clang --depth=1
        git clone https://gitlab.com/Jprimero15/aosp-clang-18.0.0 clang --depth=1
        git clone https://github.com/snowwolf725/AnyKernel3 -b oneplus7 --depth=1
        rm -rf AnyKernel3/.git
    - name: Get kernelsu-next sourcecode
      run: |
        curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next 
    - name: Build Kernel
      run: |
       export PATH=$(pwd)/clang/bin/:$(pwd)/aarch64/bin/:$PATH
       export ARCH=arm64
       export SUBARCH=arm64
       export LD=ld.lld
       make $KERNEL_CMDLINE $KERNEL_DEFCONFIG CC="ccache clang"
       make $KERNEL_CMDLINE CC="ccache clang" -j$(nproc --all)
       cp out/arch/arm64/boot/Image AnyKernel3
    - name: Upload Kernel-SU
      uses: actions/upload-artifact@v4
      with:
        name: OP7-DerpFest14-kernel-KSU-LXC-${{ steps.get_version.outputs.VERSION }}
        path: "AnyKernel3/*"
